#!C:\WinP\bd311\bu\WPy64-31160\python-3.11.6.amd64\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
